spring:
  jpa:
    database: h2
#    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true #NOT FOR PRODUCTION  

  datasource:
#    url: jdbc:h2:~/training-jpa2
    url: jdbc:h2:tcp://localhost/~/training-jpa2
#    url: jdbc:postgresql://localhost:5432/jpatraining
    username: jpatraining
    password: password

    hikari:
      maximum-pool-size: 5
      connection-test-query: select 1
      
      