spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

  datasource:
    url: jdbc:h2:~/training-jpa
    username: training

    hikari:
      maximum-pool-size: 5
      connection-test-query: select 1
      
      